// copyright: Copyright (c) 2026 Lowell D. Thomas
//   license: MIT (https://opensource.org/license/MIT)
//
// Generated by apg-esm, Version 1.1.0
interface GrammarOpcode {
  type: number;
  gl: number;
  go: number;
  index?: number;
  children?: number[];
  min?: number;
  max?: number;
  string?: number[];
  empty?: boolean;
}

interface GrammarRule {
  name: string;
  lower: string;
  index: number;
  opcodes?: GrammarOpcode[];
}

interface GrammarUdt {
  name: string;
  lower: string;
  index: number;
  empty: boolean;
}

interface GrammarObject {
  grammarObject: string;
  rules: GrammarRule[]
  udts: GrammarUdt[];
  toString(): string;
}

export default class grammar implements GrammarObject{
  grammarObject: string;
  rules: GrammarRule[];
  udts: GrammarUdt[];

  constructor() {
    // ```
    // SUMMARY
    //      rules = 6
    //       udts = 0
    //    opcodes = 24
    //        ---   ABNF original opcodes
    //        ALT = 0
    //        CAT = 4
    //        REP = 3
    //        RNM = 11
    //        TLS = 0
    //        TBS = 3
    //        TRG = 0
    //        ---   SABNF superset opcodes
    //        UDT = 0
    //        AND = 1
    //        NOT = 2
    // characters = [97 - 99]
    // ```
    /* OBJECT IDENTIFIER (magic number for internal parser use) */
    this.grammarObject = 'grammarObject';

    /* RULES */
    this.rules = [];
    this.rules[0] = { name: 'S', lower: 's', index: 0 };
    this.rules[1] = { name: 'AB', lower: 'ab', index: 1 };
    this.rules[2] = { name: 'BC', lower: 'bc', index: 2 };
    this.rules[3] = { name: 'a', lower: 'a', index: 3 };
    this.rules[4] = { name: 'b', lower: 'b', index: 4 };
    this.rules[5] = { name: 'c', lower: 'c', index: 5 };

    /* UDTS */
    this.udts = [];

    /* OPCODES */
    /* S */
    this.rules[0].opcodes = [];
    this.rules[0].opcodes[0] = { type: 2, children: [1,6,8,9], gl: 0, go: 4 };// CAT
    this.rules[0].opcodes[1] = { type: 12, gl: 0, go: 4 };// AND
    this.rules[0].opcodes[2] = { type: 2, children: [3,4], gl: 0, go: 6 };// CAT
    this.rules[0].opcodes[3] = { type: 4, index: 1, gl: 0, go: 6 };// RNM(AB)
    this.rules[0].opcodes[4] = { type: 13, gl: 0, go: 9 };// NOT
    this.rules[0].opcodes[5] = { type: 4, index: 4, gl: 0, go: 10 };// RNM(b)
    this.rules[0].opcodes[6] = { type: 3, min: 0, max: Infinity, gl: 0, go: 13 };// REP
    this.rules[0].opcodes[7] = { type: 4, index: 3, gl: 0, go: 14 };// RNM(a)
    this.rules[0].opcodes[8] = { type: 4, index: 2, gl: 0, go: 16 };// RNM(BC)
    this.rules[0].opcodes[9] = { type: 13, gl: 0, go: 19 };// NOT
    this.rules[0].opcodes[10] = { type: 4, index: 5, gl: 0, go: 20 };// RNM(c)

    /* AB */
    this.rules[1].opcodes = [];
    this.rules[1].opcodes[0] = { type: 2, children: [1,2,4], gl: 1, go: 5 };// CAT
    this.rules[1].opcodes[1] = { type: 4, index: 3, gl: 1, go: 5 };// RNM(a)
    this.rules[1].opcodes[2] = { type: 3, min: 0, max: 1, gl: 1, go: 7 };// REP
    this.rules[1].opcodes[3] = { type: 4, index: 1, gl: 1, go: 8 };// RNM(AB)
    this.rules[1].opcodes[4] = { type: 4, index: 4, gl: 1, go: 12 };// RNM(b)

    /* BC */
    this.rules[2].opcodes = [];
    this.rules[2].opcodes[0] = { type: 2, children: [1,2,4], gl: 2, go: 5 };// CAT
    this.rules[2].opcodes[1] = { type: 4, index: 4, gl: 2, go: 5 };// RNM(b)
    this.rules[2].opcodes[2] = { type: 3, min: 0, max: 1, gl: 2, go: 7 };// REP
    this.rules[2].opcodes[3] = { type: 4, index: 2, gl: 2, go: 8 };// RNM(BC)
    this.rules[2].opcodes[4] = { type: 4, index: 5, gl: 2, go: 12 };// RNM(c)

    /* a */
    this.rules[3].opcodes = [];
    this.rules[3].opcodes[0] = { type: 6, string: [97], gl: 3, go: 6 };// TBS

    /* b */
    this.rules[4].opcodes = [];
    this.rules[4].opcodes[0] = { type: 6, string: [98], gl: 4, go: 6 };// TBS

    /* c */
    this.rules[5].opcodes = [];
    this.rules[5].opcodes[0] = { type: 6, string: [99], gl: 5, go: 6 };// TBS
  }
  // The `toString()` member will display the original grammar file(s) that produced these opcodes.
  toString(): string {
    let str = "";
      str += "S = &(AB !b) *a BC !c\r\n";
      str += "AB = a [AB] b\r\n";
      str += "BC = b [BC] c\r\n";
      str += "a = %s\"a\"\r\n";
      str += "b = %s\"b\"\r\n";
      str += "c = %s\"c\"\r\n";
    return str;
  }
}
