#!/usr/bin/env node
node JavaScript/basic/fixed.js
node JavaScript/basic/separate.js
node JavaScript/basic/single.js
node JavaScript/ast.js
node JavaScript/lookAhead.js
node JavaScript/stats.js
node JavaScript/trace.js
node JavaScript/traceSabnf.js
node JavaScript/udt.js
