// copyright: Copyright (c) 2026 Lowell D. Thomas
//   license: MIT (https://opensource.org/license/MIT)
//
// Generated by apg-esm, Version 1.1.0
interface GrammarOpcodeBase {
  type: number;
  gl: number;
  go: number;
}

type GrammarOpcode =
  | (GrammarOpcodeBase & { children: number[] })
  | (GrammarOpcodeBase & { index: number })
  | (GrammarOpcodeBase & { min: number; max: number })
  | (GrammarOpcodeBase & { string: number[] });

interface GrammarRule {
  name: string;
  lower: string;
  index: number;
  opcodes?: GrammarOpcode[];
}

interface GrammarUdt {
  name: string;
  lower: string;
  index: number;
  empty: boolean;
}

export default function grammar(this: {
  grammarObject: string;
  rules: GrammarRule[];
  udts: GrammarUdt[];
  toString(): string;
}) {
  // ```
  // SUMMARY
  //      rules = 9
  //       udts = 0
  //    opcodes = 35
  //        ---   ABNF original opcodes
  //        ALT = 3
  //        CAT = 5
  //        REP = 8
  //        RNM = 10
  //        TLS = 6
  //        TBS = 0
  //        TRG = 3
  //        ---   SABNF superset opcodes
  //        UDT = 0
  //        AND = 0
  //        NOT = 0
  // characters = [43 - 101]
  // ```
  /* OBJECT IDENTIFIER (magic number for internal parser use) */
  this.grammarObject = 'grammarObject';

  /* RULES */
  this.rules = [];
  this.rules[0] = { name: 'float', lower: 'float', index: 0 };
  this.rules[1] = { name: 'sign', lower: 'sign', index: 1 };
  this.rules[2] = { name: 'decimal', lower: 'decimal', index: 2 };
  this.rules[3] = { name: 'integer', lower: 'integer', index: 3 };
  this.rules[4] = { name: 'dot', lower: 'dot', index: 4 };
  this.rules[5] = { name: 'fraction', lower: 'fraction', index: 5 };
  this.rules[6] = { name: 'exponent', lower: 'exponent', index: 6 };
  this.rules[7] = { name: 'esign', lower: 'esign', index: 7 };
  this.rules[8] = { name: 'exp', lower: 'exp', index: 8 };

  /* UDTS */
  this.udts = [];

  /* OPCODES */
  /* float */
  this.rules[0].opcodes = [];
  this.rules[0].opcodes[0] = { type: 2, children: [1,3,4], gl: 3, go: 11 };// CAT
  this.rules[0].opcodes[1] = { type: 3, min: 0, max: 1, gl: 3, go: 11 };// REP
  this.rules[0].opcodes[2] = { type: 4, index: 1, gl: 3, go: 12 };// RNM(sign)
  this.rules[0].opcodes[3] = { type: 4, index: 2, gl: 3, go: 18 };// RNM(decimal)
  this.rules[0].opcodes[4] = { type: 3, min: 0, max: 1, gl: 3, go: 26 };// REP
  this.rules[0].opcodes[5] = { type: 4, index: 6, gl: 3, go: 27 };// RNM(exponent)

  /* sign */
  this.rules[1].opcodes = [];
  this.rules[1].opcodes[0] = { type: 1, children: [1,2], gl: 4, go: 11 };// ALT
  this.rules[1].opcodes[1] = { type: 7, string: [43], gl: 4, go: 11 };// TLS
  this.rules[1].opcodes[2] = { type: 7, string: [45], gl: 4, go: 17 };// TLS

  /* decimal */
  this.rules[2].opcodes = [];
  this.rules[2].opcodes[0] = { type: 1, children: [1,8], gl: 5, go: 11 };// ALT
  this.rules[2].opcodes[1] = { type: 2, children: [2,3], gl: 5, go: 11 };// CAT
  this.rules[2].opcodes[2] = { type: 4, index: 3, gl: 5, go: 11 };// RNM(integer)
  this.rules[2].opcodes[3] = { type: 3, min: 0, max: 1, gl: 5, go: 19 };// REP
  this.rules[2].opcodes[4] = { type: 2, children: [5,6], gl: 5, go: 20 };// CAT
  this.rules[2].opcodes[5] = { type: 4, index: 4, gl: 5, go: 20 };// RNM(dot)
  this.rules[2].opcodes[6] = { type: 3, min: 0, max: 1, gl: 5, go: 24 };// REP
  this.rules[2].opcodes[7] = { type: 4, index: 5, gl: 5, go: 25 };// RNM(fraction)
  this.rules[2].opcodes[8] = { type: 2, children: [9,10], gl: 6, go: 12 };// CAT
  this.rules[2].opcodes[9] = { type: 4, index: 4, gl: 6, go: 12 };// RNM(dot)
  this.rules[2].opcodes[10] = { type: 4, index: 5, gl: 6, go: 16 };// RNM(fraction)

  /* integer */
  this.rules[3].opcodes = [];
  this.rules[3].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 7, go: 11 };// REP
  this.rules[3].opcodes[1] = { type: 5, min: 48, max: 57, gl: 7, go: 13 };// TRG

  /* dot */
  this.rules[4].opcodes = [];
  this.rules[4].opcodes[0] = { type: 7, string: [46], gl: 8, go: 11 };// TLS

  /* fraction */
  this.rules[5].opcodes = [];
  this.rules[5].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 9, go: 11 };// REP
  this.rules[5].opcodes[1] = { type: 5, min: 48, max: 57, gl: 9, go: 13 };// TRG

  /* exponent */
  this.rules[6].opcodes = [];
  this.rules[6].opcodes[0] = { type: 2, children: [1,2,4], gl: 10, go: 11 };// CAT
  this.rules[6].opcodes[1] = { type: 7, string: [101], gl: 10, go: 11 };// TLS
  this.rules[6].opcodes[2] = { type: 3, min: 0, max: 1, gl: 10, go: 15 };// REP
  this.rules[6].opcodes[3] = { type: 4, index: 7, gl: 10, go: 16 };// RNM(esign)
  this.rules[6].opcodes[4] = { type: 4, index: 8, gl: 10, go: 23 };// RNM(exp)

  /* esign */
  this.rules[7].opcodes = [];
  this.rules[7].opcodes[0] = { type: 1, children: [1,2], gl: 11, go: 11 };// ALT
  this.rules[7].opcodes[1] = { type: 7, string: [43], gl: 11, go: 11 };// TLS
  this.rules[7].opcodes[2] = { type: 7, string: [45], gl: 11, go: 17 };// TLS

  /* exp */
  this.rules[8].opcodes = [];
  this.rules[8].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 12, go: 11 };// REP
  this.rules[8].opcodes[1] = { type: 5, min: 48, max: 57, gl: 12, go: 13 };// TRG

  // The `toString()` function will display the original grammar file(s) that produced these opcodes.
  this.toString = function toString(){
    let str = "";
    str += ";\r\n";
    str += "; ABNF for a floating point number\r\n";
    str += ";\r\n";
    str += "float    = [sign] decimal [exponent]\r\n";
    str += "sign     = \"+\" / \"-\"\r\n";
    str += "decimal  = integer [dot [fraction]]\r\n";
    str += "decimal  =/ dot fraction\r\n";
    str += "integer  = 1*%d48-57\r\n";
    str += "dot      = \".\"\r\n";
    str += "fraction = 1*%d48-57\r\n";
    str += "exponent = \"e\" [esign] exp\r\n";
    str += "esign    = \"+\" / \"-\"\r\n";
    str += "exp      = 1*%d48-57\r\n";
    return str;
  }
}
